export {default as VendorList} from './VendorList'
export {default as InventoryList} from './InventoryList'
export {default as WelcomePage} from './WelcomePage'
export {default as OrderForm} from './OrderForm'
export {default as OrderList} from './OrderList'
export {default as SettingPage} from './SettingPage'
